### ISSUE TITLE
Add Leaflet widget to draw geometries and save as WKT

### ISSUE THREAD

**Issue by reinvantveer** [erfgoed-en-locatie/geo-googledocs#1]
- [x] Create menu item
- [x] Add Leaflet plugin on widget 'page' 
- [x] With [Draw](https://github.com/Leaflet/Leaflet.draw) plugin and 
- [x] With [wellknown](https://raw.githubusercontent.com/mapbox/wellknown/master/wellknown.js) plugin
- [x] Add 'Save' button to insert geometry as WKT in document on selected field
- [ ] Store last used position and zoom level for next feature to draw
- [ ] Update WKT serialization after edit event
- [ ] Pass existing WKT string in document to widget for editing

**Comment by jobspierings** [comment]
wont fix.
